# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 09:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutor4u', '0003_auto_20161120_0609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, unique=True)),
                ('password', models.CharField(default='', max_length=200)),
                ('star', models.IntegerField(default=0)),
                ('email', models.EmailField(default='', max_length=200)),
                ('gender', models.CharField(default='', max_length=200)),
                ('biography', models.CharField(default='', max_length=2000)),
                ('major', models.CharField(default='', max_length=200)),
                ('currentyear', models.CharField(default='', max_length=200)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('course1', models.CharField(default='', max_length=200)),
                ('course2', models.CharField(default='', max_length=200)),
                ('course3', models.CharField(default='', max_length=200)),
                ('grade1', models.CharField(default='', max_length=200)),
                ('grade2', models.CharField(default='', max_length=200)),
                ('grade3', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
